export const phpToPythonMap = [
  { php: '$variable', python: 'variable', note: '去掉 $ 前缀' },
  { php: 'echo / print', python: 'print()', note: '统一用 print 函数' },
  { php: '. (字符串拼接)', python: 'f-string / +', note: '推荐使用 f-string' },
  { php: 'array()', python: '[] / {} / ()', note: '列表/字典/元组' },
  { php: 'array_push()', python: 'list.append()', note: '方法调用代替函数' },
  { php: 'count()', python: 'len()', note: '内置函数' },
  { php: 'isset()', python: "'key' in dict / is not None" },
  { php: 'empty()', python: 'not value' },
  { php: 'null', python: 'None', note: '首字母大写' },
  { php: 'true / false', python: 'True / False', note: '首字母大写' },
  { php: '&& / || / !', python: 'and / or / not', note: '更自然的关键词' },
  { php: 'elseif', python: 'elif', note: '缩写不同' },
  { php: 'foreach ($arr as $v)', python: 'for v in arr:', note: '更简洁' },
  { php: 'function', python: 'def', note: '定义函数' },
  { php: '__construct', python: '__init__', note: '构造函数' },
  { php: '$this', python: 'self', note: '引用当前实例' },
  { php: '->', python: '.', note: '对象访问' },
  { php: '::', python: '.', note: '类访问' },
  { php: 'try/catch', python: 'try/except', note: '异常处理' },
  { php: 'require/include', python: 'import', note: '引入模块' },
  { php: 'use Namespace\\Class', python: 'from module import Class' },
  { php: 'composer require', python: 'pip install / poetry add' },
  { php: '// 注释', python: '# 注释', note: '单行注释' },
  { php: '/* */ 注释', python: '""" """ 注释', note: '多行/文档注释' },
  { php: 'sprintf()', python: 'f-string', note: 'f"{var}" 更简洁强大' },
  { php: 'json_encode/json_decode', python: 'json.dumps/json.loads', note: 'json 模块' },
  { php: 'array_map()', python: 'map() / 列表推导式', note: '推荐列表推导式' },
  { php: 'array_filter()', python: 'filter() / 列表推导式', note: '推荐列表推导式' },
  { php: 'usort($arr, fn)', python: 'sorted(arr, key=)', note: 'key 参数更优雅' },
  { php: 'array_combine()', python: 'dict(zip(keys, values))', note: 'zip 创建字典' },
  { php: 'fn($x) => $x * 2', python: 'lambda x: x * 2', note: 'lambda 只能单行' },
  { php: 'static method', python: '@staticmethod / @classmethod', note: '装饰器代替关键字' },
  { php: 'new static()', python: 'cls() in @classmethod', note: '工厂模式' },
  { php: 'class with __construct', python: '@dataclass', note: '自动生成样板代码' },
  { php: 'Eloquent ORM', python: 'SQLAlchemy 2.0', note: 'Python 主流 ORM' },
  { php: 'PHPUnit', python: 'pytest', note: '更简洁的测试框架' },
  { php: '...$args (解包)', python: '*args / **kwargs', note: 'Python 解包更灵活' },
];
